dependencies:
  # - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    # remappings: '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
    remappings: '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  default: development
wallets:
  priv_key: ${INFOGYVES_KEY}