dependencies:
  # - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - smartcontractkit/chainlink-brownie-contracts@0.4.0
  - OpenZeppelin/openzeppelin-contracts@4.5.0
compiler:
  solc:
    remappings:
      # - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
# Path to environment variables
dotenv: .env
# Addresses:
networks:
  default: development
  development:
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 250000000000000000
    gas_price_link: 1000000000
  rinkeby:
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    weth_key: '0xD1DECc6502cc690Bc85fAf618Da487d886E54Abe'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    fee: 250000000000000000
    gas_price_link: 1000000000
    verify: True
  ganache-infogyves:
    verify: False
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    weth_key: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
# Wallet
wallets:
  priv_key: ${INFOGYVES_PRIVATE_KEY}
# Gas Limit Settings
settings:
  gas_limit: "400000"
